//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Participant
    {
        public System.Guid participant_id { get; set; }
        public string session_id { get; set; }
        public string phoneNumber { get; set; }
        public string ParticipantName { get; set; }
        public string facility { get; set; }
    
        public virtual ParticipantAnswer ParticipantAnswer { get; set; }
    }
}
